[package]
name = "TOTP"
version = "0.1.0"
edition = "2024"

[dependencies]
otpauth = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossterm = "0.28"
aes-gcm = "0.10.3"
argon2 = "0.5.0"
rpassword = "7.2.0"
rand_core = "0.6.4"